#!/usr/bin/env bash
# display info about subdomains of helixr.tech

func () {
    subdomain="$2"
    RECORD=$(dig "$1" | awk '/IN/ && $1 !~ /^;/ {print $4}')
    NAME=$(dig "$1" | awk '/IN/ && $1 !~ /^;/ {print $5}')
    echo "The subdomain ${subdomain} is a ${RECORD} record and points to ${NAME}"
}

if [ -z "$2" ]; then
    func "www.$1" "www"
    func "lb-01.$1" "lb-01"
    func "web-01.$1" "web-01"
    func "web-02.$1" "web-02"
else
    func "$2.$1" $2
fi
