#!/usr/bin/env bash
# loop to print count 1-20 with conditional formatting
count=1
while [ $count -lt 21 ]
do
    echo $count
    case $count in
	4) echo bad luck from China
	    ;;
	9) echo bad luck from Japan
	    ;;
	17) echo bad luck from Italy
	    ;;
    esac
    count=$((count + 1))
done
