#!/usr/bin/env bash
# display time for 12 hrs and 59 min
hour=0
while [ $hour -lt 13 ]
do
    echo "Hour: $hour"
    min=1
    while [ $min -lt 60 ]
    do
	echo $min
	min=$((min + 1))
    done
    hour=$((hour + 1))
done
