#!/usr/bin/env bash
# script that privides info on the holbertonschool file

if [ ! -e holbertonschool ]; then
    echo holbertonschool file does not exist
else
    echo holbertonschool file exists
    if [ ! -s holbertonschool ]; then
	echo holbertonschool file is empty
    else
	echo holbertonschool file is not empty
    fi
    if [ -f holbertonschool ]; then
	echo holbertonschool is a regular file
    fi
fi
